### ISSUE TITLE
RESTful API를 설계한다. 

### ISSUE THREAD

**Issue by Martin0o0** [KHUMON-EDU/Backend#3]
## 상세 내용

- [ ]  클라이언트단과의 REST 통신을 위해 JSON 형식의 API 시트(엔드포인트)를 설계한다.

**Comment by pl0901** [comment]
시트 설계 초안본 완성했습니다. 
https://www.notion.so/pl0901/API-sheet-e899b463d4bb4188a90d4cde377a9fe0?pvs=4
확인 부탁드려요!

**Comment by Martin0o0** [comment]
> 시트 설계 초안본 완성했습니다. https://www.notion.so/pl0901/API-sheet-e899b463d4bb4188a90d4cde377a9fe0?pvs=4 확인 부탁드려요!

확인했습니다!
