### ISSUE TITLE
프론트에서 로그아웃시 나오는 로그

### ISSUE THREAD

**Issue by van1164** [KHUMON-EDU/Backend#31]
## 버그 발생 내용

로그아웃 api에 요청을 보내면 다음과 같이 나오는데 잘 된건가요..?

![image](https://github.com/KHUMON-EDU/Backend/assets/52437971/ed550f53-35ba-437c-a4ee-f68dee54bf95)

**Comment by Martin0o0** [comment]
레디스를 활성화 시켜주어야할 듯 합니다..!
